### ISSUE TITLE
Ability to create locations without having to go back to the base of the world

### ISSUE THREAD

**Issue by ImperialXT** [brunosardinepi/dungeonomics#100]
Currently, when you want to create a location you need to go to the World itself and use the menu to get the create option there, and then choose its parent which can be quite deep. It'd be nice to be able to create a new location while viewing an existing Location. 

At a glance, the necessary change would need to be made in dungeonomics/locations/templates/locations/card_header.html, however, I'm unsure of how exactly to go about doing that otherwise.

An example would be below.

World (Can only create location while at this level, presently)
    - Continent
        - Town/Village
          - Inn/Store/Whatever

**Comment by brunosardinepi** [comment]
Ya this is pretty annoying. I'll add it to the community vote list, and it gets my vote for sure. Thanks for pointing this out.

**Comment by brunosardinepi** [comment]
@ImperialXT i just finished this, it'll get pushed on Friday with our other updates
