### ISSUE TITLE
@-link popup list is not styled correctly in the NPC textfields

### ISSUE THREAD

**Issue by sruebner** [brunosardinepi/dungeonomics#101]
I noticed, that since the update of the site, the popup list is not styled correctly, when you try to type an @ on the edit NPC page. As far as I know, on all other pages the list is styled correctly (see attached screenshots). I can reproduce this on every NPC and in the browsers Firefox (59.0.2) and Chrome (65.0.3325.181) on macOS High Sierra.

You can still select an entry by klicking on it, but if you try to select something with the arrow-down-key, no highlight shows up, so that you have to use the mouse.

### styling correct
![correct-styling](https://user-images.githubusercontent.com/3474352/38173995-99e965f4-35c6-11e8-9d0e-1caf699777e0.png)

### styling missing
![wrong-styling](https://user-images.githubusercontent.com/3474352/38173996-9a08af22-35c6-11e8-95d1-29a9ea2fcfc5.png)

**Comment by brunosardinepi** [comment]
Thanks for catching this. I was not carrying the CSS files over to these forms so it was showing up with the missing styling. The fix will get pushed this Friday.

**Comment by sruebner** [comment]
No problem! I love your website, and it is good to see that someone is actively developing and improving it!
