### ISSUE TITLE
Map section

### ISSUE THREAD

**Issue by TheMadMagpie** [brunosardinepi/dungeonomics#27]
"add section where users can upload maps, notes, handouts etc. And something to easily view D&D 5e monsters, within legal limits"

**Comment by brunosardinepi** [comment]
converting this to a consolidation of worlds/locations into locations, and then adding an image field for locations

**Comment by brunosardinepi** [comment]
i tried the migration today and it failed. jake's like of issues:

Create Section - Done goofed error
Edit Chapter - Done goofed error
Print campaign - Done goofed error
Create location - Done goofed error
Edit location - Done goofed error
Create Players, Monsters, NPCs - Done goofed error
Edit Players, Monsters, NPCs - Done goofed error
Create Items/spells - Done goofed error
Edit Items/spells - Done goofed error
Click link to tagged location - Either we messed up, or you did. It was probably you...
