### ISSUE TITLE
random tables

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/dungeonomics#35]
from reddit.

Random encounters, random loot generator, random weather conditions, random events while camping outdoors, etc!

**Comment by pmauldin** [comment]
Question regarding this, spells, items, etc.

Would you want these things to be new tabs at the top next to NPCs/Monsters or should there be like a new "Resources" tab for the aforementioned non-character things? Just a thought

**Comment by brunosardinepi** [comment]
Seems like a “Resources” tab would be a good way to go. The resources, like monsters/NPCs, should be global and usable in multiple campaigns, so I think having a “Resources” section outside of the “Campaigns" section is a smart move. Then you could just link to them like you can with monsters/NPCs.

**Comment by brunosardinepi** [comment]
Update: "items" have now been created

**Comment by pmauldin** [comment]
Awesome! I'm away from my desktop for the holidays and unfortunately my laptop sucks too much for dev. As soon as I'm back (early Jan) I'll hopefully be able to contribute again.

**Comment by brunosardinepi** [comment]
No rush man. Happy holidays
