### ISSUE TITLE
world building

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/dungeonomics#41]
discuss creating assets for worlds/cities/countries etc that can be used like assets

**Comment by pmauldin** [comment]
Question regarding this, spells, items, etc. 

Would you want these things to be new tabs at the top next to NPCs/Monsters or should there be like a new "Resources" tab for the aforementioned non-character things? Just a thought

**Comment by brunosardinepi** [comment]
Seems like a “Resources” tab would be a good way to go. The resources, like monsters/NPCs, should be global and usable in multiple campaigns, so I think having a “Resources” section outside of the “Campaigns" section is a smart move. Then you could just link to them like you can with monsters/NPCs.
